In [21]:
import numpy as np
from typing import Optional, Tuple

def agh_superfast_lu(a: np.matrix) -> Optional[Tuple[np.matrix, np.matrix]]:
    """Perform LU decomposition of a matrix.
    
    :param a: matrix
    :return: (L, U)
    """
    n = a.shape[0]
    L = np.matrix(np.zeros(n*n).reshape(n,n), dtype=float)
    U = np.matrix(np.zeros(n*n).reshape(n,n), dtype=float)
    for i in range(n):
        L.itemset((i,i), 1)
    try:
        for i in range(n):
            for j in range(i, n):
                sum = a.item((i, j))
                for k in range(i):
                    sum -= L.item((i, k)) * U.item((k, j))
                U.itemset((i, j), sum)
                sum = a.item((j, i))
                if j != i:
                    for k in range(i):
                        sum -= L.item((j, k)) * U.item((k, i))
                    sum /= U.item((i, i))
                    L.itemset((j, i), sum)
    except:
        pass
    return (L, U)

a = np.matrix([[5,3,2],[1,2,0],[3,0,4]])

L, U = agh_superfast_lu(a)

print(L)
print(U)
print(L*U)

[[ 1.          0.          0.        ]
 [ 0.2         1.          0.        ]
 [ 0.6        -1.28571429  1.        ]]
[[ 5.          3.          2.        ]
 [ 0.          1.4        -0.4       ]
 [ 0.          0.          2.28571429]]
[[5.00000000e+00 3.00000000e+00 2.00000000e+00]
 [1.00000000e+00 2.00000000e+00 0.00000000e+00]
 [3.00000000e+00 1.14194368e-16 4.00000000e+00]]


In [15]:
def minor(arr,i,j) -> np.matrix:
    return arr[np.array(list(range(i))+list(range(i+1,arr.shape[0])))[:,np.newaxis],
               np.array(list(range(j))+list(range(j+1,arr.shape[1])))]

def agh_superfast_check_spd(a: np.matrix) -> bool:
    """Check whether a matrix is symmetric and positive-definite (SPD).
    
    :param a: matrix
    """
    n = a.shape[0]
    tmp = a
    for i in range(n-1, 0, -1):
        tmp = minor(tmp, i, i)
        if np.linalg.det(tmp) < 0:
            return false
    return np.all(a == a.transpose())

a = np.matrix([[2,-1,0],[-1,2,-1],[0,-1,2]])

b = np.matrix([[1,2],[3,4]])

print(agh_superfast_check_spd(a))
print(agh_superfast_check_spd(b))

True
False


In [ ]:
def agh_superfast_cholesky(a: np.matrix) -> Optional[np.matrix]:
    """Perform a Cholesky decomposition of a matrix.
    
    :param a: _
    :return:  _
    """
    pass