In [32]:
import numpy as np
def gaussian_elimination_no_pivoting(a_arg: np.matrix, b_arg: np.matrix) -> np.matrix:
    a = a_arg.copy()
    b = b_arg.copy()
    a = a.astype(float)
    b = b.astype(float)
    n = a.shape[0]
    for curr_row in range(n):
        factor = a.item(curr_row, curr_row)
        for i in range(curr_row, n):
            v = a.item((curr_row, i))
            a.itemset((curr_row, i), v / factor)
        b.itemset((curr_row, 0), b.item((curr_row, 0)) / factor)
        for sub_row in range(n):
            if sub_row != curr_row:
                factor = a.item((sub_row, curr_row))
                for column in range(curr_row, n):
                    pv = a.item((curr_row, column))
                    v = a.item((sub_row, column))
                    a.itemset((sub_row, column), v - pv * factor)
                b.itemset((sub_row, 0), b.item((sub_row, 0)) - b.item((curr_row, 0)) * factor)
    return b

A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
               [2.2660, 1.9950,  1.2120, 8.0080],
               [8.8500, 5.6810,  4.5520, 1.3020],
               [6.7750, -2.253,  2.9080, 3.9700]])

b = np.matrix([9.5740, 7.2190, 5.7300, 6.2910]).transpose()

print(gaussian_elimination_no_pivoting(A, b))

print(np.linalg.solve(A, b))

[[ 0.21602477]
 [-0.00791511]
 [ 0.63524333]
 [ 0.74617428]]
[[ 0.21602477]
 [-0.00791511]
 [ 0.63524333]
 [ 0.74617428]]


In [51]:
def gaussian_elimination_with_pivoting(a_arg: np.matrix, b_arg: np.matrix) -> np.matrix:
    a = a_arg.copy()
    b = b_arg.copy()
    a = a.astype(float)
    b = b.astype(float)
    n = a.shape[0]
    redir = list(range(n))
    maxs = np.absolute(a).max(1).transpose().tolist()[0]
    for curr_row in range(n):
        #pivoting
        curr_max = 0
        j = curr_row
        for i in range(curr_row, n):
            if a.item((redir[i], curr_row)) / maxs[redir[i]] > curr_max:
                j = i
                curr_max = a.item((redir[i], curr_row)) / maxs[redir[i]]
        redir[j], redir[curr_row] = redir[curr_row], redir[j]
        #end pivoting
        factor = a.item(redir[curr_row], curr_row)
        for i in range(curr_row, n):
            v = a.item((redir[curr_row], i))
            a.itemset((redir[curr_row], i), v / factor)
        b.itemset((redir[curr_row], 0), b.item((redir[curr_row], 0)) / factor)
        for sub_row in range(n):
            if sub_row != curr_row:
                factor = a.item((redir[sub_row], curr_row))
                for column in range(curr_row, n):
                    pv = a.item((redir[curr_row], column))
                    v = a.item((redir[sub_row], column))
                    a.itemset((redir[sub_row], column), v - pv * factor)
                b.itemset((redir[sub_row], 0), 
                          b.item((redir[sub_row], 0)) - 
                          b.item((redir[curr_row], 0)) * factor)
    return np.matrix(list(map(lambda x: b.item((x, 0)), redir))).transpose()

A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
               [2.2660, 1.9950,  1.2120, 8.0080],
               [8.8500, 5.6810,  4.5520, 1.3020],
               [6.7750, -2.253,  2.9080, 3.9700]])

b = np.matrix([9.5740, 7.2190, 5.7300, 6.2910]).transpose()

print(gaussian_elimination_with_pivoting(A, b))

print(np.linalg.solve(A, b))

[[ 0.21602477]
 [-0.00791511]
 [ 0.63524333]
 [ 0.74617428]]
[[ 0.21602477]
 [-0.00791511]
 [ 0.63524333]
 [ 0.74617428]]
